name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: gcjam 2020 - npm install and test
      run: |
        cd 2020
        docker run -v $(pwd):/app -w /app/test node npm install
        docker run -it -v $(pwd):/app -w /app/test node npm test

    - name: gcjam 2021 - npm install and test
      run: |
        cd 2021
        docker run -v $(pwd):/app -w /app/test node npm install
        docker run -it -v $(pwd):/app -w /app/test node npm test
